name: copyparty-macvlan

services:
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    
    # Run as an unprivileged user
    user: "1000:1000"

    init: true

    env_file:
      - .env

    restart: unless-stopped

    # This container is attached to a macvlan network. With macvlan, the container has its own LAN IP, so port 
    # publishing is unnecessary and effectively not used.
    # ports:
    #   - "3923:3923"

    volumes:
      - ./:/cfg:z
      - ${COPY_PARTY_FOLDER}:/w:z

    environment:
      TZ: ${COPY_PARTY_TZ}

      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)

      PYTHONUNBUFFERED: 1
      # ensures log-messages are not delayed (but can reduce speed a tiny bit)

    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter 
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s

    networks:
      lan_macvlan:
        ipv4_address: ${COPY_PARTY_IP}

networks:
  lan_macvlan:
    external: true
    name: lan_macvlan
